version: '3'
services:
  #node
  node:
    build: ./docker/node
    image: node
    container_name: node
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm start]

  # MySQL
  mysql:
    build: ./docker/mysql
    image: mysql:5.6.40
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db/mysql_data:/var/lib/mysql
      - ./docker/mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: node_project
      MYSQL_USER: node_project
      MYSQL_ROOT_PASSWORD: A3mFp9RKF3
      MYSQL_PASSWORD: Crni793ScH
      TZ: 'Asia/Tokyo'

  # nginx
  nginx:
    build: ./docker/nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node

