version: '3'
services:
  #node
  node:
    build: ./docker/node
    image: node
    container_name: node
    volumes:
      - ./app:/src
    command: [sh, -c, npm install && npm start]

  # MySQL
  mysql:
    build: ./docker/mysql
    image: mysql:5.6.40
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: node_project
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'

  # nginx
  nginx:
    build: ./docker/nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - node

