module.exports = {
  'DB_INFO1': 'INSERT SUCCESS',
  'DB_INFO2': 'SELECT SUCCESS',
  'DB_INFO3': 'UPDATE SUCCESS',
  'DB_INFO4': 'DELETE SUCCESS',

  'DB_ERROR1': 'INSERT ERROR',
  'DB_ERROR2': 'SELECT ERROR',
  'DB_ERROR3': 'UPDATE ERROR',
  'DB_ERROR4': 'DELETE ERROR',
};
