module.exports = {
  'DB_INFO1': 'INSERT SUCCESS',
  'DB_INFO2': 'SELECT SUCCESS',
  'DB_INFO3': 'UPDATE SUCCESS',
  'DB_INFO4': 'DELETE SUCCESS',
  'DB_INFO5': 'ONLY ONCE START',
  'DB_INFO6': 'ONLY ONCE END',

  'DB_ERROR1': 'INSERT ERROR',
  'DB_ERROR2': 'SELECT ERROR',
  'DB_ERROR3': 'UPDATE ERROR',
  'DB_ERROR4': 'DELETE ERROR',
  'DB_ERROR5': 'DATABASE ERROR',

  'ACCESS1': 'SIGNIN ACCESS',
  'ACCESS2': 'USER SIGNUP ACCESS',
  'ACCESS3': 'HOME ACCESS',
  'ACCESS4': 'QRCODE CREATE ACCESS',
  'ACCESS5': 'QRCODE ACCESS',
  'ACCESS6': 'DELAY ACCESS',
  'ACCESS7': 'ABSENCE ACCESS',
  'ACCESS8': 'DELAY LIST ACCESS',
  'ACCESS9': 'ABSENCE LIST ACCESS',

  'ERROR1': 'VALIDATION ERROR',
  'ERROR2': 'ACCESS ERROR',
  'ERROR3': 'LOGIN ERROR',

  'INFO1': 'MASTER LOGIN SACCESS',
  'INFO2': 'USER LOGIN SACCESS',
  'INFO3': 'READER LOGIN SACCESS',
  'INFO4': 'LOGIN USER',
};
